---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
   VPCCIDR:
     Description: this is first vpc
     Type: String
     Default: "10.0.0.0/24"
   TgName:
     Description: this is tg 
     Type: String
     Default: "devdevDemo"
   Env:
     Description: Env
     Type: String
     Default: "dev"
   SUBCIDR:
      Description: this is devDemo subnet1
      Type: String
      Default: "10.0.0.0/25"
   KeyName:
      Description: Keypair name
      Type: String
      Default: "devDemo"
   InstanceType:
      Description: Type of the Instannce
      Type: String
      Default: "t2.micro"
   AMI:
      Description: AMI ID
      Type: String
      Default: "ami-0ee8244746ec5d6d4"
   PublicKey:
      Description: Public key material
      Type: String
      Default: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDh1wqrNgd3JB6jLrY7IOb0wm1NiZjn64UZPVdfhJMlwM+1JkOb3tFHx+Xb9CQWBy7ZprvCa2e2tcjTSUgHKWgg+8zxSaoOrgE+APM8UoQ3NIRpaG3UJGSDLQqPJyWhh5nS0g/rHjMpuFYX8n/rsdhHnDxPfvAu4exPHtQ0qEU5wkSe6I95je5DIDM+laAbeBFfhe7XZAE5chi7jt6FwaiSKorpVPKvw+72lIayqLaZYg2zY0/8ipbHGs62h4j3Et+aYE8SVsoz9KaK9+jvDL0aze8A+rzfQw45A4Rrl2Pj1RKF3RrYi/UuLYB2dqWUQxpzUaZ7qCQk34OYFmPA2U8zHJVv4AbXEz78XNbaa2HfyplXcOQm7iBuLLdo7VfVDd6EKNAUgYCQBWdGxuqgC4G2iTa7VjzgZUaZFzZArJN60dnWBlfgsb0Oy0x9jl6LJrzAKfJ/MKD0G0MAOTcC/hsJDNNWJTM2aNpH9a0isQBc1zp64UqBNMt1B7wUV9j7wF0= gopipacha@jarvis.local"
   AVAILZONE:
      Type: String
      Default: "us-west-2a" #us-east-2abc other 2a/b/c
   SUBCIDR2:
      Description: this is devDemo subnet2
      Type: String
      Default: "10.0.0.128/25"
   AVAILZONE2:
      Type: String
      Default: "us-west-2b"
   ALBname:
     Type: String
     Default: "multi-cft"
   secret:
     Type: String
     Default: "arn:aws:secretsmanager:ap-south-1:446058500452:secret:gitlab-VKoHi8"
   roleCreate:
     Description: should i create role or not
     Default: create
     Type: String
     AllowedValues: [create,notCreate]
Conditions:
   create: !Equals [!Ref roleCreate, create]

Resources:
   EC2Instance:
      Type: 'AWS::EC2::Instance'
      Properties:
        ImageId: !Ref AMI
        InstanceType: "t2.micro"
        KeyName: "devDemo"
        SubnetId: "subnet-0d137bc42ba0bbac5"
        SecurityGroupIds:
          - "sg-0b47d0183d9a29913"
        #BlockDeviceMappings:
         # - DeviceName: /dev/sda1
          #  Ebs:
           #   VolumeSize: 250
        UserData:
          Fn::Base64: !Sub |
              #!/bin/bash
              apt update -y
              apt install -y nginx
              systemctl start nginx.service
              systemctl enable nginx.service
        Tags:
          - Key: Name
            Value:  "test-server"
   